# src/config/config.yaml

audio:
  sample_rate: 22050
  pitch_factor: 0.7
  stretch_rate: 0.8

data:
  path: "data/annotations/annotations.csv"
  target_column: "label"

model:
  type: "lstm"
  params:
    hidden_size: 128
    num_layers: 2
    dropout: 0.2

training:
  epochs: 30
  batch_size: 32
  lr: 0.001
